export const ONE_PROMPT_MAX_REFERENCE_IMAGES = 9;
export const ONE_PROMPT_IMAGE_PROMPT_GENERATION_TARGET_CHARS = 3000;
export const ONE_PROMPT_IMAGE_PROMPT_COMPACTION_THRESHOLD_CHARS = 4200;
export const ONE_PROMPT_IMAGE_PROMPT_MAX_CHARS = 5000;
